INSERT INTO state (state_id, state_name) VALUES ('TX', 'Texas'); 
INSERT INTO state (state_id, state_name) VALUES ('MT', 'Montana'); 
INSERT INTO state (state_id, state_name) VALUES ('MN', 'North Dakota'); 
INSERT INTO state (state_id, state_name) VALUES ('ND', 'North Dakota'); 
INSERT INTO state (state_id, state_name) VALUES ('WA', 'Washington'); 
INSERT INTO state (state_id, state_name) VALUES ('ME', 'Maine'); 
INSERT INTO state (state_id, state_name) VALUES ('AK', 'Alaska'); 
INSERT INTO state (state_id, state_name) VALUES ('CA', 'California'); 
INSERT INTO state (state_id, state_name) VALUES ('MI', 'Michigan'); 
INSERT INTO state (state_id, state_name) VALUES ('NY', 'New York'); 
INSERT INTO state (state_id, state_name) VALUES ('AZ', 'Arizona'); 
INSERT INTO state (state_id, state_name) VALUES ('NM', 'New Mexico'); 
INSERT INTO state (state_id, state_name) VALUES ('ID', 'Idaho'); 
INSERT INTO state (state_id, state_name) VALUES ('VT', 'Vermont'); 